FORMAT: 1A
HOST: http://closets.apiblueprint.org/api/v2

# Closets API
Documentation of API Closets 2.0.

# Group Product
Api Design for new data from closets 2.0
## GET : Product  [/product/detail{?product_id}{?uid}]

### List Product Detail [GET]
+ Parameters

    + uid : 1 (number) - user uid login 

+ Response 200 (application/json)

        {
            "product" : {
                "icon_filename":"icon.png",
                "product_status_message": "you have purchased this item"
            }
        }

# Group Feed
Api Design For Follower Following Feed Discover Recommendation
## GET : Followers And Followees [/following/follow{?limit}{?uid}{?page}{?type}]

### List Follow [GET]
+ Parameters

    + limit : 10  (number)
    + uid : 1 (number)
    + page : 1 (number)
    + type : followees (string) - followees or followers
    
+ Response 200 (application/json)

        {
            "type" : "followees",
            "data" :
            [
               {
                    "seller":{
                        "uid":2,
                        "nickname" : "test 2",
                        "avatar" : "test2.jpg",
                        "items_count":10,
                        "followed":true
                    },
                    "product" : [
                        {
                            "id":0,
                            "image":"test.jpg",
                            "status":"open",
                            "created_at":123452,
                            "updated_at":123452
                        },
                        {
                            "id":1,
                            "image":"test1.jpg",
                            "status":"open",
                            "created_at":123452,
                            "updated_at":123452
                        },
                        {
                            "id":2,
                            "image":"test1.jpg",
                            "status":"open",
                            "created_at":123452,
                            "updated_at":123452
                        },
                        {
                            "id":3,
                            "image":"test1.jpg",
                            "status":"open",
                            "created_at":123452,
                            "updated_at":123452
                        },
                        {
                            "id":4,
                            "image":"test1.jpg",
                            "status":"open",
                            "created_at":123452,
                            "updated_at":123452
                        }
                    ]
                }
            ],
            "limit" : 20,
            "page" : 1
        }

## POST : Follow Unfollow Action [/following/follow]
### Follow Unfollow Action [POST]

+ Request (application/json)

        {
            "followee_uid":20,
            "uid": 2,
            "action" : "follow/unfollow"
        }

+ Response 200 (application/json)

        {
            "status" : true,
            "message" : "following successful / unfollow successful"
        }


## GET : Discover [/following/discover{?limit}{?uid}{?page}{?country_code}{?refresh}]

### List Discover [GET]
+ Parameters

    + limit : 20 (number)
    + uid : 1 (number)
    + page : 1 (number)
    + country_code : SG (string)
    + refresh : 23123 (number) - timestamp when the page is first loaded
    
+ Response 200 (application/json)

        {
            "data" : 
            [
                {
                    
                    "product":{
                        "id":0,
                        "image":"test.jpg",
                        "status":"open",
                        "created_at":123452,
                        "updated_at":123452
                    }
                },
                {
                    "product":{
                        "id":1,
                        "image":"test.jpg",
                        "status":"open",
                        "created_at":123452,
                        "updated_at":123452
                    }
                },
                {
                    "product":{
                        "id":2,
                        "image":"test.jpg",
                        "status":"open",
                        "created_at":123452,
                        "updated_at":123452
                    }
                }
            ],
            "limit" : 20,
            "page" : 1
        }

## GET : Recommended [/following/recommended{?limit}{?uid}{?page}{?country_code}{?language_code}{?refresh}]
### List Recommended [GET]

+ Parameters

    + limit : 20 (number)
    + uid : 1 (number)
    + page : 1 (number)
    + country_code : SG (string)
    + language_code : EN (string)
    + refresh : 1232 (number) - timestamp when the page is first loaded 
    
+ Response 200 (application/json)

        {
            "data" : 
            [
                {
                    "type":"spotlight",
                    "type_label":"recommended by",
                    "followee_uid":0,
                    "seller":{
                        "uid":2,
                        "nickname" : "test 2",
                        "avatar" : "test2.jpg",
                        "items_count":10
                    },
                    "product" : [
                        {
                            "id":0,
                            "image":"test.jpg",
                            "status":"open",
                            "created_at":123452,
                            "updated_at":123452
                        },
                        {
                            "id":1,
                            "image":"test1.jpg",
                            "created_at":123452,
                            "updated_at":123452
                        },
                        {
                            "id":2,
                            "image":"test1.jpg",
                            "created_at":123452,
                            "updated_at":123452
                        },
                        {
                            "id":3,
                            "image":"test1.jpg",
                            "created_at":123452,
                            "updated_at":123452
                        },
                        {
                            "id":4,
                            "image":"test1.jpg",
                            "created_at":123452,
                            "updated_at":123452
                        }
                    ]
                },
                {
                    "type":"liked",
                    "type_label":"based on you liked",
                    "followee_uid":0,
                    "seller":{
                        "uid":2,
                        "nickname" : "test 2",
                        "avatar" : "test2.jpg",
                        "items_count":10
                    },
                    "product" : [
                        {
                            "id":0,
                            "image":"test.jpg",
                            "created_at":123452,
                            "updated_at":123452
                        },
                        {
                            "id":1,
                            "image":"test1.jpg",
                            "created_at":123452,
                            "updated_at":123452
                        },
                        {
                            "id":2,
                            "image":"test1.jpg",
                            "created_at":123452,
                            "updated_at":123452
                        },
                        {
                            "id":3,
                            "image":"test1.jpg",
                            "created_at":123452,
                            "updated_at":123452
                        },
                        {
                            "id":4,
                            "image":"test1.jpg",
                            "created_at":123452,
                            "updated_at":123452
                        }
                    ]
                },
                {
                    "type":"followee",
                    "type_label":"recommended by",
                    "followee_uid":0,
                    "seller":{
                        "uid":2,
                        "nickname" : "test 2",
                        "avatar" : "test2.jpg",
                        "items_count":10
                    },
                    "product" : [
                        {
                            "id":0,
                            "image":"test.jpg",
                            "created_at":123452,
                            "updated_at":123452
                        },
                        {
                            "id":1,
                            "image":"test1.jpg",
                            "created_at":123452,
                            "updated_at":123452
                        },
                        {
                            "id":2,
                            "image":"test1.jpg",
                            "created_at":123452,
                            "updated_at":123452
                        },
                        {
                            "id":3,
                            "image":"test1.jpg",
                            "created_at":123452,
                            "updated_at":123452
                        },
                        {
                            "id":4,
                            "image":"test1.jpg",
                            "created_at":123452,
                            "updated_at":123452
                        }
                    ]
                }
                
            ],
            "limit" : 20,
            "page" : 1
        }

## GET : Following [/following/feed/{?limit}{?uid}{?page}{?country_code}]
### List Following Feed [GET]

+ Parameters

    + limit : 20 (number)
    + uid : 1 (number)
    + page : 1 (number)
    + country_code : SG (string)
    
+ Response 200 (application/json)

        {
            "data" : 
            [
                {
                    "seller":{
                        "uid":2,
                        "nickname" : "test 2",
                        "avatar" : "test2.jpg"
                    },
                    "product" : {
                        "id":0,
                        "image":"test.jpg",
                        "title":"women leather",
                        "brand_name":"PRADA",
                        "likes_count":0,
                        "comments_count":0,
                        "liked":true,
                        "commented":true,
                        "currency_code":"SGD",
                        "description":"test",
                        "status":"open",
                        "selling_price":123.5,
                        "country_code":"SG",
                        "created_at":123452,
                        "updated_at":123452
                    }
                }
            ],
            "limit" : 20,
            "page" : 1
        }

# Group Activity And Conversation
Api Design For activity such as social feed,conversation listing, conversation detail

## POST : Social Activity Feed [/activity/social]
order by updated_at and unseen per page 5
### List Social feed [POST]
+ Request

        {
            "limit" : 20,
            "uid"   : 1,
            "page"  : 1,
            "language_code":"EN",
            "load_id" : [1,2,3,5]
        }

    
+ Response 200 (application/json) 

        {
            "data" : [
                {
                   "sender" : {
                        "uid" : 3,
                        "nickname" : "A3",
                        "avatar"   : "test4.jpg"
                    },
                    "social_feed" : {
                        "id" :1,
                        "recipient_uid" : 2,
                        "destination_page" : "pdt detail",
                        "system_message_code" : "liked",
                        "message":"test",
                        "is_seen":true,
                        "is_opened":true,
                        "created_at":21331313,
                        "updated_at":12312312
                    },
                    "product":{
                        "id":2134,
                        "image":"product4.jpg",
                        "status":"sold"
                    }
                },
                {
                    "sender" : {
                        "uid" : 4,
                        "nickname" : "A4",
                        "avatar"   : "test4.jpg"
                    },
                    "social_feed" : {
                        "id" :1,
                        "recipient_uid" : 2,
                        "destination_page" : "pdt detail",
                        "system_message_code" : "liked",
                        "message":"test",
                        "is_seen":true,
                        "is_opened":true,
                        "created_at":21331313,
                        "updated_at":12312312
                    },
                    "product":{
                        "id":2134,
                        "image":"product4.jpg",
                        "status":"sold"
                    }
                },
                {
                    "sender" : {
                        "uid" : 5,
                        "nickname" : "A5",
                        "avatar"   : "test5.jpg"
                    },
                    "social_feed" : {
                        "id" :1,
                        "recipient_uid" : 2,
                        "destination_page" : "pdt detail",
                        "system_message_code" : "liked",
                        "message":"test",
                        "is_seen":true,
                        "is_opened":true,
                        "created_at":21331313,
                        "updated_at":12312312
                    },
                    "product":{
                        "id":2134,
                        "image":"product5.jpg",
                        "status":"sold"
                    }
                }
            ],
            "limit": 20,
            "page" : 1
        }
           

## GET : Buying Activity Feed [/activity/buying{?limit}{?uid}{?page}{?language_code}]
### List Buying Feed [POST]
+ Parameters

    + limit : 20 (number)
    + uid : 1 (number)
    + page : 1
    + language_code : EN (string)

+ Response 200 (application/json)

        {
            "data" : [
                {
                     "last_seller_sender" : {
                        "uid" : -1,
                        "nickname" : "Reebonz Atelier",
                        "avatar"   : "reebonz_atelier.jpg"
                    },
                    "conversation" : {
                        "id" :1,
                        "last_buyer_destination_page" : "pdt detail",
                        "last_buyer_icon_filename":"icon.png",
                        "last_buyer_system_message_code" : "liked",
                        "last_message":"test",
                        "last_negotiation_status":"-",
                        "is_buyer_archive":false,
                        "is_seller_archive":false,
                        "is_seen":true,
                        "is_opened_buyer":true,
                        "is_opened_seller":true,
                        "icon_filename":"icon",
                        "created_at":21331313,
                        "updated_at":12312312
                    },
                    "product":{
                        "id":213,
                        "image":"product.jpeg",
                        "status":"sold"
                    }
                },
                {
                     "last_seller_sender" : {
                        "uid" : 2,
                        "nickname" : "Ardani",
                        "avatar"   : "test_ardani.jpg"
                    },
                    "conversation" : {
                        "id" :1,
                        "last_buyer_destination_page" : "pdt detail",
                        "last_buyer_icon_filename":"icon.png",
                        "last_buyer_system_message_code" : "liked",
                        "last_message":"test",
                        "last_negotiation_status":"-",
                        "is_buyer_archive":false,
                        "is_seller_archive":false,
                        "is_seen":true,
                        "is_opened_buyer":true,
                        "is_opened_seller":true,
                        "icon_filename":"icon",
                        "created_at":21331313,
                        "updated_at":12312312
                    },
                    "product":{
                        "id":213,
                        "image":"product.jpeg",
                        "status":"sold"
                    }
                },
                {
                     "last_seller_sender" : {
                        "uid" : 3,
                        "nickname" : "Eko",
                        "avatar"   : "test_Eko.jpg"
                    },
                    "conversation" : {
                        "id" :1,
                        "last_buyer_destination_page" : "pdt detail",
                        "last_buyer_icon_filename":"icon.png",
                        "last_buyer_system_message_code" : "liked",
                        "last_message":"test",
                        "last_negotiation_status":"-",
                        "is_buyer_archive":false,
                        "is_seller_archive":false,
                        "is_seen":true,
                        "is_opened_buyer":true,
                        "is_opened_seller":true,
                        "icon_filename":"icon",
                        "created_at":21331313,
                        "updated_at":12312312
                    },
                    "product":{
                        "id":213,
                        "image":"product.jpeg",
                        "status":"sold"
                    }
                }
            ],
            "limit": 20,
            "page" : 1
        }

## GET : Selling Activity Feed [/activity/selling{?limit}{?uid}{?page}{?type}{?language_code}]
### List Selling feed [POST]
+ Parameters

    + limit : 20 (number)
    + uid : 1 (number)
    + page : 1
    + language_code: EN (string)

+ Response 200 (application/json)

        {
            "data" : [
                {
                     "last_buyer_sender" : {
                        "uid" : -1,
                        "nickname" : "Reebonz Atelier",
                        "avatar"   : "reebonz_atelier.jpg"
                    },
                    "conversation" : {
                        "id" :1,
                        "last_seller_destination_page" : "pdt detail",
                        "last_seller_icon_filename":"icon.png",
                        "last_seller_system_message_code" : "liked",
                        "last_message":"test",
                        "last_negotiation_status":"-",
                        "is_buyer_archive":false,
                        "is_seller_archive":false,
                        "is_seen":true,
                        "is_opened_buyer":true,
                        "is_opened_seller":true,
                        "icon_filename":"icon",
                        "created_at":21331313,
                        "updated_at":12312312
                    },
                    "product":{
                        "id":213,
                        "image":"product.jpeg",
                        "status":"sold"
                    }
                },
                {
                     "last_buyer_sender" : {
                        "uid" : 2,
                        "nickname" : "Ardani",
                        "avatar"   : "test_ardani.jpg"
                    },
                    "conversation" : {
                        "id" :1,
                        "last_seller_destination_page" : "pdt detail",
                        "last_seller_icon_filename":"icon.png",
                        "last_seller_system_message_code" : "liked",
                        "last_message":"test",
                        "last_negotiation_status":"-",
                        "is_buyer_archive":false,
                        "is_seller_archive":false,
                        "is_seen":true,
                        "is_opened_buyer":true,
                        "is_opened_seller":true,
                        "icon_filename":"icon",
                        "created_at":21331313,
                        "updated_at":12312312
                    },
                    "product":{
                        "id":213,
                        "image":"product.jpg",
                        "status":"sold"
                    }
                },
                {
                     "last_buyer_sender" : {
                        "uid" : 3,
                        "nickname" : "Eko",
                        "avatar"   : "test_Eko.jpg"
                    },
                    "conversation" : {
                        "id" :1,
                        "last_seller_destination_page" : "pdt detail",
                        "last_seller_icon_filename":"icon.png",
                        "last_seller_system_message_code" : "liked",
                        "last_message":"test",
                        "last_negotiation_status":"-",
                        "is_buyer_archive":false,
                        "is_seller_archive":false,
                        "is_seen":true,
                        "is_opened_buyer":true,
                        "is_opened_seller":true,
                        "icon_filename":"icon",
                        "created_at":21331313,
                        "updated_at":12312312
                    },
                    "product":{
                        "id":213,
                        "image":"product.jpg",
                        "status":"sold"
                    }
                }
            ],
            "limit": 20,
            "page" : 1
        }
        

## POST : Action Chat Conversation [/activity/send_chat]
for seller and buyer
param {type}
    - message_sent
    - photo_sent
    - offer_made
    - offer_withdrawn
    - offer_revise
    - offer_declined
    - offer_accepted
### Action Conversation chat [POST]
+ Request

        {
           "type" : "message_sent",
           "sender_uid":23,
           "conversation_id":24,
           "image":"-",
           "offer_price":0,
           "currency_code":"SGD",
           "message":"bla bla bla",
           "product_id":1,
           "negotiation_status":"-"
        }
        
+ Response 200 (application/json)

        {
            "data" : {
                "status":true,
                "message":"sent"
            }
        }

## GET : Chat Conversation [/activity/chat{?conversation_id}{?limit}{?page}{?sender_uid}{?language_code}]
### List Conversation chat [POST]
+ Parameters

    + conversation_id : 1 (number)
    + sender_uid:2 (number)
    + limit : 20 (number)
    + page : 1 (number)
    + language_code : EN (string)

+ Response 200 (application/json)

        {
            "data" : {
                "product":{
                    "id" : 12,
                    "brand_name":"prada",
                    "image":"product.jpeg",
                    "category":"bags",
                    "currency_code":"SGD",
                    "country_code":"SG",
                    "title":"saint laurent",
                    "description":" sample description",
                    "status":"open"
                },
                "seller": {
                    "uid":1231,
                    "nickname":"yessika",
                    "avatar":"yessika.jpg"
                },
                "buyer": {
                    "uid":1232,
                    "nickname":"ardani",
                    "avatar":"ardani.jpg"
                },
                "conversation" :{
                    "id":1,
                    "other_buyers":0,
                    "buyer_currency_code":"SGD",
                    "seller_currency_code":"SGD",
                    "buyer_last_offer_price":900,
                    "seller_last_offer_price":900,
                    "last_payout_price":800,
                    "last_negotiation_status":"-",
                    "last_offer_price_commission":123
                },
                "conversation_detail" :[
                    {
                        "id" : 1,
                        "message_image":null,
                        "system_message_code":"offer",
                        "sender_uid":1231,
                        "buyer_currency_code":"SGD",
                        "seller_currency_code":"SGD",
                        "seller_offer_price":0,
                        "buyer_offer_price":0,
                        "seller_payout_price":0,
                        "order_id":0,
                        "icon_filename":"cart",
                        "message":"[seller_name] accepted your offer of [offer_price]. Make payment by [date] to secure your item.",
                        "token_message":{
                            "seller_name" : "shopoholic",
                            "date" : "1.45 today",
                            "offer_price":"SGD 100"
                        },
                        "negotiation_status":null,
                        "destination_path":"-",
                        "created_at":12313131
                    },
                    {
                        "id" : 2,
                        "message_image":null,
                        "system_message_code":"offer",
                        "sender_uid":2,
                        "buyer_currency_code":"SGD",
                        "seller_currency_code":"SGD",
                        "seller_offer_price":0,
                        "buyer_offer_price":0,
                        "seller_payout_price":0,
                        "order_id":0,
                        "icon_filename":"cart",
                        "message":"ITEM PURCHASED\n Congrats! You purchased this item from [seller_name]",
                        "token_message":{
                            "seller_name":"shopoholic"
                        },
                        "negotiation_status":null,
                        "destination_path":"-",
                        "created_at":12313131
                    },
                    {
                        "id" : 3,
                        "message_image":null,
                        "system_message_code":"offer",
                        "sender_uid":-1,
                        "buyer_currency_code":"SGD",
                        "seller_currency_code":"SGD",
                        "seller_offer_price":0,
                        "buyer_offer_price":0,
                        "seller_payout_price":0,
                        "order_id":0,
                        "icon_filename":"cart",
                        "message":"test",
                        "negotiation_status":null,
                        "destination_path":"-",
                        "created_at":12313131
                    }   
                ]
            },
            "limit" : 20,
            "page" : 1
        }


## GET : Count Notification [/notification/activity{?uid}]
### Count activity notification unseen [GET]
+ Parameters

    + uid : 1 (number)
    
+ Response 200 (application/json)

        {
            "data" :{
                "notification" : 23
            }
        }

# Group Action Trigger Center
Api Design for action trigger center

## POST : Trigger Center Chat [/trigger/chat]
for seller and buyer
param {type}
    - message_sent
    - photo_sent
    

### Action trigger chat [POST]
+ Request

        {
            "sender_uid" :1,
            "recepient_uid" : 2,
            "product_id":1,
            "type":"message_sent/photo_sent",
            "message" : "sample message",
        }

+ Response 200 (application/json)

        {
            "status":true,
            "message":"trigger action sent"
        }

## POST : Trigger Center Offer [/trigger/offer]
for seller and buyer
param {type}
    - offer_made
    - offer_withdrawn
    - offer_revise
    - offer_declined/offer_accepted

### Action trigger offer [POST]
+ Request

        {
            "type":"offer_made/offer_withdrawn/offer_revise/offer_declined/offer_accepted",
            "sender_uid" :1,
            "recepient_uid" : 2,
            "product_id":1,
            "offer_price":0,
            "language_code":"EN",
            "buyer_currency_code":"SGD",
            "seller_currency_code":"SGD"
        }

+ Response 200 (application/json)

        {
            "status":true,
            "message":"trigger action sent"
        }


## POST : Trigger Center Cart [/trigger/cart]
param {type}
type cart :
    - pending_bank_transfer
    - pending_offline_ipp
    - pending_cancelled

### Action trigger cart [POST]
+ Request

        {
            "trigger_type":"pending_bank_transfer",
            "product_id":1,
            "language_code":"EN"
        }

+ Response 200 (application/json)

        {
            "status":true,
            "message":"trigger action sent"
        }

## POST : Trigger Center Post Sales [/trigger/postsales]
param {type}
type postsales :
    - order_new
    - order_collection_scheduled
    - order_collection_succeeded
    - order_collection_failed
    - order_authentication_succeeded
    - order_delivery_succeeded
    - order_delivery_failed
    - order_completed
    - order_payment_completed
    - order_cancelled
    - cancelled_refund_completed
    - order_authentication_failed
    - authfailed_refund_completed
    - authfailed_delivery_scheduled
    - authfailed_delivery_succeeded
    - authfailed_delivery_failed
    - return_collection_scheduled
    - return_collection_succeeded
    - return_collection_failed
    - return_refund_completed
    - return_delivery_scheduled
    - return_delivery_succeeded
    - return_delivery_failed

### Action trigger post sales [POST]
+ Request

        {
            "trigger_type":"order_new",
            "product_id":1,
            "schedule_collection_expiry":"1 business day",
            "refund_promise":"1 business day",
            "language_code":"EN"
        }

+ Response 200 (application/json)

        {
            "status":true,
            "message":"trigger action sent"
        }

## POST : Trigger Center Follow [/trigger/following]
param {type}
type following :
    - user_register
### Action trigger follow [POST]
+ Request

        {
            "trigger_type":"user_register",
            "sender_uid" :1,
        }

+ Response 200 (application/json)

        {
            "status":true,
            "message":"trigger action sent"
        }

## POST : Trigger Like [/trigger/like]
for like product
### Action trigger like [POST]
+ Request

        {
            "product_id":1,
            "sender_uid":1,
            "action":"like/unlike",
            "seller_uid":12,
        }

+ Response 200 (application/json)

        {
            "status":true,
            "message":"trigger action sent"
        }

## POST : Trigger Comment [/trigger/comment]
for comment
### Action trigger comment [POST]
+ Request

        {
            "product_id":1,
            "seller_uid":12,
            "sender_uid":1,
            "message":"sample message",
            "action":"insert/delete"
        }

+ Response 200 (application/json)

        {
            "status":true,
            "message":"trigger action sent"
        }

## POST : Trigger Product [/trigger/product]
for product - item_sold - item_price_drop - item_deleted
### Action trigger product [POST]
+ Request

        {
            "old":{
                "product_id":1,
                "status":"new",
                "seller_uid":23,
                "title":"bags",
                "price":123
            },
            "new":{
                "product_id":1,
                "status":"open",
                "seller_uid":23,
                "title":"bags",
                "price":200
            }
        }

+ Response 200 (application/json)

        {
            "status":true,
            "message":"trigger action sent"
        }

## POST : Trigger Listing [/trigger/listing]
for update status product by atelier 
### Action trigger listing [POST]
+ Request

        {
            "product_id":1,
            "product_title":"bags",
            "status":"open"
        }

+ Response 200 (application/json)

        {
            "status":true,
            "message":"trigger action sent"
        }
